### ISSUE TITLE
Pillow has unmentionned build dependencies

### ISSUE THREAD

**Issue by mrdaemon** [glasnost/kremlin#11]
Building pillow on windows is obnoxious, and on everything else it requires libjpeg, libpng and a bunch of stuff that the README doesn't mention.

The easy way is to use easy_install in the virtualenv on windows to fetch a binary package.

Both of these things should be clarified at some point in the README before release, or at least somewhere.

**Comment by ghostfreeman** [comment]
We could easily kill this bird by summarizing the use of easy_install for Windows. Another option (more work) is to just throw a Vagrantfile in there and hope they're smart enough to use that, but that deserves its own story.
